# Generated by Django 5.1.7 on 2025-03-31 20:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('personal', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='textcontainer',
            options={'verbose_name': 'Title', 'verbose_name_plural': 'Text Containers'},
        ),
    ]
