# Generated by Django 5.1.7 on 2025-04-22 04:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personal', '0002_alter_textcontainer_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='textcontainer',
            name='text',
            field=models.TextField(),
        ),
    ]
