# Generated by Django 5.1.7 on 2025-04-25 02:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personal', '0004_imagecontainer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imagecontainer',
            name='image',
            field=models.ImageField(upload_to='media/'),
        ),
    ]
