# Generated by Django 5.1.7 on 2025-04-26 01:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personal', '0005_alter_imagecontainer_image'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='imagecontainer',
            options={'verbose_name': 'Header', 'verbose_name_plural': 'Header'},
        ),
        migrations.AddField(
            model_name='imagecontainer',
            name='welcome',
            field=models.CharField(default='', max_length=200),
        ),
    ]
