# Generated by Django 5.1.7 on 2025-04-26 04:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personal', '0007_speakers'),
    ]

    operations = [
        migrations.AddField(
            model_name='speakers',
            name='bio',
            field=models.TextField(default=''),
        ),
    ]
