# Generated by Django 5.1.7 on 2025-04-26 04:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personal', '0008_speakers_bio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='speakers',
            name='first_name',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='speakers',
            name='last_name',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='speakers',
            name='specialty',
            field=models.CharField(default='', max_length=50),
        ),
    ]
