# Generated by Django 5.1.7 on 2025-04-26 04:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personal', '0009_alter_speakers_first_name_alter_speakers_last_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='speakers',
            name='image',
            field=models.ImageField(upload_to='media/speakers/'),
        ),
    ]
