# Generated by Django 5.1.7 on 2025-04-27 01:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('personal', '0010_alter_speakers_image'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='speakers',
            options={'verbose_name': 'Speakers', 'verbose_name_plural': 'Speakers'},
        ),
        migrations.AlterModelOptions(
            name='textcontainer',
            options={'verbose_name': 'Section', 'verbose_name_plural': 'Sections'},
        ),
    ]
