# Generated by Django 5.1.7 on 2025-04-27 01:37

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personal', '0011_alter_speakers_options_alter_textcontainer_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='registration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('phone', models.IntegerField(max_length=15, validators=[django.core.validators.MinLengthValidator(5)])),
                ('email', models.EmailField(max_length=100)),
                ('parent_email', models.EmailField(max_length=100)),
            ],
            options={
                'verbose_name': 'Applicants',
                'verbose_name_plural': 'Applicants',
            },
        ),
    ]
