# Generated by Django 5.1.7 on 2025-04-27 01:37

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personal', '0012_registration'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registration',
            name='phone',
            field=models.CharField(max_length=15, validators=[django.core.validators.MinLengthValidator(5)]),
        ),
    ]
