# Generated by Django 5.1.7 on 2025-04-27 02:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('personal', '0013_alter_registration_phone'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='speakers',
            new_name='Speaker',
        ),
    ]
