# Generated by Django 5.1.7 on 2025-04-27 03:43

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personal', '0014_rename_speakers_speaker'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registration',
            name='parent_email',
            field=models.EmailField(default='', max_length=100, verbose_name="Parent's Email"),
        ),
        migrations.AlterField(
            model_name='registration',
            name='phone',
            field=models.CharField(max_length=15, validators=[django.core.validators.MinLengthValidator(10)]),
        ),
    ]
