# Generated by Django 5.1.7 on 2025-04-27 04:03

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personal', '0015_alter_registration_parent_email_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='events',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.CharField(max_length=50)),
                ('location', models.CharField(max_length=100)),
                ('name', models.CharField(max_length=50)),
                ('info', models.TextField()),
            ],
            options={
                'verbose_name': 'Events',
                'verbose_name_plural': 'Events',
            },
        ),
        migrations.AlterField(
            model_name='registration',
            name='parent_email',
            field=models.EmailField(max_length=100, verbose_name="Parent's Email"),
        ),
        migrations.AlterField(
            model_name='registration',
            name='phone',
            field=models.CharField(max_length=15, validators=[django.core.validators.MinLengthValidator(9)]),
        ),
    ]
