# Generated by Django 5.1.7 on 2025-04-27 22:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personal', '0016_events_alter_registration_parent_email_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Highlighted_Speaker',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='media/speakers/')),
                ('first_name', models.CharField(default='', max_length=50)),
                ('last_name', models.CharField(default='', max_length=50)),
                ('specialty', models.CharField(default='', max_length=50)),
                ('bio', models.TextField(default='')),
            ],
            options={
                'verbose_name': 'Speakers',
                'verbose_name_plural': 'Speakers',
            },
        ),
    ]
