# Generated by Django 5.1.7 on 2025-04-27 22:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('personal', '0017_highlighted_speaker'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='highlighted_speaker',
            options={'verbose_name': 'Highlighted Speakers', 'verbose_name_plural': 'Highlighted Speakers'},
        ),
    ]
