# Generated by Django 5.1.7 on 2025-04-28 04:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personal', '0018_alter_highlighted_speaker_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='speaker',
            name='image',
            field=models.ImageField(upload_to='media/highlighted_speakers/'),
        ),
    ]
