# Generated by Django 5.1.7 on 2025-04-28 04:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('personal', '0020_alter_highlighted_speaker_image_alter_speaker_image'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='highlighted_speaker',
            options={'verbose_name': 'Highlighted Speaker', 'verbose_name_plural': 'Highlighted Speakers'},
        ),
    ]
