# Generated by Django 5.1.7 on 2025-05-05 00:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personal', '0021_alter_highlighted_speaker_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='textcontainer',
            options={'ordering': ['order'], 'verbose_name': 'Section', 'verbose_name_plural': 'Sections'},
        ),
        migrations.AddField(
            model_name='textcontainer',
            name='order',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
