# Generated by Django 5.1.7 on 2025-05-05 01:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personal', '0022_alter_textcontainer_options_textcontainer_order'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='events',
            options={'ordering': ['order'], 'verbose_name': 'Events', 'verbose_name_plural': 'Events'},
        ),
        migrations.AlterModelOptions(
            name='highlighted_speaker',
            options={'ordering': ['order'], 'verbose_name': 'Highlighted Speaker', 'verbose_name_plural': 'Highlighted Speakers'},
        ),
        migrations.AlterModelOptions(
            name='speaker',
            options={'ordering': ['order'], 'verbose_name': 'Speakers', 'verbose_name_plural': 'Speakers'},
        ),
        migrations.RemoveField(
            model_name='events',
            name='location',
        ),
        migrations.AddField(
            model_name='events',
            name='order',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='highlighted_speaker',
            name='order',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='speaker',
            name='order',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
