# Generated by Django 5.1.7 on 2025-05-05 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personal', '0023_alter_events_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='highlighted_speaker',
            name='first_name',
            field=models.CharField(default='', max_length=50, verbose_name='First Name'),
        ),
        migrations.AlterField(
            model_name='highlighted_speaker',
            name='specialty',
            field=models.CharField(default='', max_length=50, verbose_name='Title'),
        ),
        migrations.AlterField(
            model_name='speaker',
            name='first_name',
            field=models.CharField(default='', max_length=50, verbose_name='First Name'),
        ),
        migrations.AlterField(
            model_name='speaker',
            name='specialty',
            field=models.CharField(default='', max_length=50, verbose_name='Title'),
        ),
    ]
